added tie-breaking rules
praveenscience/GSSoC21-Leaderboard-Projects pull request #7
Opened 2021-04-23 19:53 UTC by Ritikace01

I have added the necessary tie-breaking rules in the leaderboard. Request you to review them and merge them by the earliest.

For you information, I have listed the tie-breaking rules for you, so that you can review them at your end.
There are basically three major ranking rules:-
1. Sort them according to their scores.
2. If scores are same, then rank on basis of who has solved issues from more levels.
3. If still not resolved, then rank on basis of PR count.
4. If still not resolved, then rank them alphabetically.

2021-04-23 21:08 UTC, praveenscience requested changes
Let me show you where you should change it.
https://github.com/praveenscience/GSSoC21-Leaderboard-Projects/blob/gh-pages/leaderboard.js#L6-L9

2021-04-23 21:08 UTC, praveenscience commented on App.js
> +     }
Great logic, but wrong place! 😅

2021-05-16 03:56 UTC, Vishal-raj-1 commented on App.js
> +     }
@Ritikace01 ??

2021-05-24 20:18 UTC, praveenscience commented
Added to the generator manually. 😊

2021-05-24 20:18 UTC, closed without merging